Repository LM-channel-team-project/kiwee.dev, pull requests merged in 2021-06, with the labels that each got.

#44 프로필 페이지 데이터 바인딩, swr hook 추가, 아티클 스켈레톤 추가, api 수정
  front/.prettierrc
  front/src/components/ErrorFallback/PostCardLayout/FallbackPostCardLayout.tsx
  front/src/components/ErrorFallback/Profile/FallbackProfileUser.tsx
  front/src/components/ErrorFallback/SkeletonBlock.tsx
  front/src/components/PostCardLayout/PostCardLayout.tsx
  front/src/components/Profile/ProfileStats.tsx
  front/src/components/Profile/ProfileStatsPostCardList.tsx
  front/src/components/Profile/ProfileUser.tsx
  front/src/components/Skeleton/PostCardLayout/PostCard/SkeletonPostCard.tsx
  front/src/components/Skeleton/PostCardLayout/PostCard/index.tsx
  front/src/components/Skeleton/PostCardLayout/SKeletonPostCardLayout.tsx
  front/src/components/Skeleton/PostCardLayout/index.tsx
  front/src/context/MutationObserverContext.tsx
  front/src/hooks/swr/useDeleteErrorCache.ts
  front/src/hooks/swr/useGetArticleInfos.ts
  front/src/hooks/swr/useGetArticles.ts
  front/src/hooks/swr/useGetMe.ts
  front/src/hooks/useUpdateArticleInfo.ts
  front/src/pages/_app.tsx
  front/src/pages/api/article/index.ts
  front/src/pages/api/articles/[articleId].ts
  front/src/pages/api/articles/comments.ts
  front/src/pages/api/articles/index.ts
  front/src/pages/api/auth/[...nextauth].ts
  front/src/pages/api/bookmarks/index.ts
  front/src/pages/api/histories/index.ts
  front/src/pages/api/history/index.ts
  front/src/pages/api/likes/index.ts
  front/src/pages/api/provider/me.ts
  front/src/pages/api/provider/rss.ts
  front/src/pages/api/test/auth/me.ts
  front/src/pages/index.tsx
  front/src/pages/profile.tsx
  front/src/types/apiType.d.ts
  front/src/types/article.d.ts
  front/src/types/response.d.ts
  front/src/wrapper/withCheckJwt.ts
Labels: 👀 리뷰 필요, 🔧 기능

#45 PostCard 관련 수정 및 API 요청 변경
  front/public/img/당근마켓.jpeg
  front/public/img/딜리버리히어로.jpeg
  front/public/img/라인.jpeg
  front/public/img/리디.jpeg
  front/public/img/마켓컬리.jpeg
  front/public/img/쏘카.jpeg
  front/public/img/왓챠.jpeg
  front/public/img/우아한형제들.jpeg
  front/public/img/이스트소프트.jpeg
  front/public/img/카카오.jpeg
  front/public/img/쿠팡.jpeg
  front/public/img/토스트.jpeg
  front/public/img/플렛팜.jpeg
  front/public/img/하이퍼커넥트.jpeg
  front/src/components/PostCardLayout/PostCard/PostCard.tsx
  front/src/components/PostCardLayout/PostCard/styles.ts
  front/src/hooks/useGetData.ts
  front/src/lib/styles/theme.ts
  front/src/pages/index.tsx
  front/src/types/styled.d.ts
Labels: ⚡️ 심플, 🔧 기능

#46 [FIX] 히스토리 업데이트 오류 수정
  api_server/src/router/historyRouter.ts
  front/src/pages/api/bookmarks/index.ts
  front/src/pages/api/histories/index.ts
  front/src/pages/api/likes/index.ts
Labels: ⚡️ 심플

#47 [ADD] 블로그 목록 조회 API 추가
  api_server/src/repository/providerRepository.ts
  api_server/src/router/providerRouter.ts
  api_server/src/service/providerService.ts
  front/src/pages/api/provider/blogs.ts
  front/src/types/response.d.ts
Labels: ⚡️ 심플

#48 기술 블로그 목록 페이지 추가 및 스타일 변경
  front/src/components/BlogCardLayout/BlogCard/BlogCard.tsx
  front/src/components/BlogCardLayout/BlogCard/index.tsx
  front/src/components/BlogCardLayout/BlogCard/styles.ts
  front/src/components/BlogCardLayout/BlogCardLayout.tsx
  front/src/components/BlogCardLayout/index.tsx
  front/src/components/BlogCardLayout/styles.ts
  front/src/components/Common/Button/button.d.ts
  front/src/components/Common/Button/style.ts
  front/src/components/Common/Icon/svg/bookmark.svg
  front/src/components/Footer/Footer.tsx
  front/src/components/Login/styles.ts
  front/src/components/Modal/Modal.tsx
  front/src/components/Modal/styles.ts
  front/src/components/Settings/ToggleDarkmode/styles.ts
  front/src/components/Settings/ToggleNewTab/ToggleNewTab.tsx
  front/src/components/Settings/common/styles.ts
  front/src/components/Settings/styles.ts
  front/src/components/header/Header.tsx
  front/src/pages/blogs.tsx
  front/src/pages/bookmark.tsx
  front/src/pages/privacy.tsx
  front/src/types/blog.d.ts
Labels: 👀 리뷰 필요, 🔧 기능

#50 Feature/fix-front
  front/package.json
  front/src/components/Common/Button/Icon/IconButton.tsx
  front/src/components/Common/Button/button.d.ts
  front/src/components/Keywords/Keywords.tsx
  front/src/components/Keywords/index.tsx
  front/src/components/Keywords/styles.ts
  front/src/components/Modal/Modal.tsx
  front/src/components/Modal/styles.ts
  front/src/components/Profile/ProfileDetails.tsx
  front/src/components/header/Header.tsx
  front/src/components/header/HeaderAuth.tsx
  front/src/pages/api/auth/[...nextauth].ts
  front/src/pages/bookmark.tsx
  front/src/pages/index.tsx
Labels: ⚡️ 심플

#52 [FIX] 오타 수정
  bootstrap.sh
Labels: ⚡️ 심플

#55 SEO 컴포넌트 추가
  front/public/assets/logo/meta-og-image.png
  front/src/components/PostCardLayout/PostCard/PostCard.tsx
  front/src/components/SEO/SEO.tsx
  front/src/components/SEO/index.ts
  front/src/components/header/Header.tsx
  front/src/lib/static/SEO.ts
  front/src/pages/profile.tsx
Labels: 👀 리뷰 필요, 🔧 기능

#56 UI 관련 업데이트
  front/public/img/logo.svg
  front/public/img/딜리버리히어로.jpeg
  front/public/img/라인.jpeg
  front/public/img/리디.jpeg
  front/public/img/쏘카.jpeg
  front/public/img/우아한형제들.jpeg
  front/public/img/카카오.jpeg
  front/public/img/쿠팡.jpeg
  front/public/img/토스트.jpeg
  front/public/img/하이퍼커넥트.jpeg
  front/src/components/Footer/Footer.tsx
  front/src/components/Settings/styles.ts
  front/src/components/header/Header.tsx
  front/src/components/header/HeaderAuth.tsx
  front/src/pages/blogs.tsx
  front/src/pages/bookmark.tsx
  front/src/pages/index.tsx
Labels: ⚡️ 심플

#57 헤더 프로필 메뉴 드랍다운 추가
  front/src/components/Profile/ProfileUser.tsx
  front/src/components/header/HeaderAuth.tsx
  front/src/components/header/HeaderMenu.tsx
  front/src/components/header/HeaderMenuItem.tsx
  front/src/lib/styles/theme.ts
  front/src/types/styled.d.ts
Labels: 🔧 기능

#58 파비콘 추가 및 모달창에 로고 추가
  front/public/favicon.ico
  front/src/components/Login/Login.tsx
  front/src/components/Login/styles.ts
  front/src/components/Modal/styles.ts
  front/src/components/Settings/styles.ts
  front/src/components/header/Header.tsx
Labels: ⚡️ 심플

#61 [FIX] 아티클이 없을 때 무한 로딩되는 오류 수정
  front/src/components/Profile/ProfileStatsPostCardList.tsx
  front/src/pages/profile.tsx
Labels: ⚡️ 심플

#62 개인정보처리방침 및 약관 페이지 추가
  front/src/components/Login/Login.tsx
  front/src/components/Login/styles.ts
  front/src/context/ModalContext.tsx
  front/src/pages/privacy.tsx
  front/src/pages/term.tsx
Labels: 👀 리뷰 필요

#63 [FIX] 링크 스타일 수정
  front/src/components/Login/styles.ts
Labels: 🐛 버그

#65 오류 수정 및 리팩토링(접근성, 404페이지, 프로필 드랍다운 메뉴, 아티클 요청 오류 등)
  front/.storybook/main.js
  front/.storybook/preview.js
  front/package-lock.json
  front/package.json
  front/public/img/logo.svg
  front/src/components/AppLayout/AppLayout.tsx
  front/src/components/Common/Button/Icon/IconButton.tsx
  front/src/components/PostCardLayout/PostCardLayout.tsx
  front/src/components/PostCardLayout/styles.ts
  front/src/components/Profile/ProfileStatsPostCardList.tsx
  front/src/components/header/Header.tsx
  front/src/components/header/HeaderAuth.tsx
  front/src/components/header/HeaderMenuItem.tsx
  front/src/hooks/swr/useDeleteErrorCache.ts
  front/src/pages/404.tsx
  front/src/pages/bookmark.tsx
  front/src/pages/index.tsx
  front/src/stories/Button.stories.tsx
  front/src/stories/Button.tsx
  front/src/stories/Header.stories.tsx
  front/src/stories/Header.tsx
  front/src/stories/Introduction.stories.mdx
  front/src/stories/Page.stories.tsx
  front/src/stories/Page.tsx
  front/src/stories/assets/code-brackets.svg
  front/src/stories/assets/colors.svg
  front/src/stories/assets/comments.svg
  front/src/stories/assets/direction.svg
  front/src/stories/assets/flow.svg
  front/src/stories/assets/plugin.svg
  front/src/stories/assets/repo.svg
  front/src/stories/assets/stackalt.svg
  front/src/stories/button.css
  front/src/stories/header.css
  front/src/stories/page.css
  front/yarn.lock
Labels: 👀 리뷰 필요, 🔧 기능

#66 스켈레톤 포스트 카드 타입 에러 수정
  front/src/components/Skeleton/PostCardLayout/PostCard/SkeletonPostCard.tsx
Labels: ⚡️ 심플

#67 파비콘 설정
  front/public/android-icon-144x144.png
  front/public/android-icon-192x192.png
  front/public/android-icon-36x36.png
  front/public/android-icon-48x48.png
  front/public/android-icon-72x72.png
  front/public/android-icon-96x96.png
  front/public/apple-icon-114x114.png
  front/public/apple-icon-120x120.png
  front/public/apple-icon-144x144.png
  front/public/apple-icon-152x152.png
  front/public/apple-icon-180x180.png
  front/public/apple-icon-57x57.png
  front/public/apple-icon-60x60.png
  front/public/apple-icon-72x72.png
  front/public/apple-icon-76x76.png
  front/public/apple-icon-precomposed.png
  front/public/apple-icon.png
  front/public/browserconfig.xml
  front/public/favicon-16x16.png
  front/public/favicon-32x32.png
  front/public/favicon-96x96.png
  front/public/manifest.json
  front/public/ms-icon-144x144.png
  front/public/ms-icon-150x150.png
  front/public/ms-icon-310x310.png
  front/public/ms-icon-70x70.png
  front/public/robots.txt
  front/src/components/Favicon/Favicon.tsx
  front/src/components/Favicon/index.ts
  front/src/components/Profile/ProfileStatsPostCardList.tsx
  front/src/hooks/useInfiniteScroll.ts
  front/src/pages/_app.tsx
  front/src/pages/bookmark.tsx
  front/src/pages/index.tsx
Labels: ⚡️ 심플

#68 README 작성
  README.md
Labels: ⚡️ 심플

#70 블로그 페이지 블로그 아이콘 클릭 시 rss 링크로 이동하는 오류 수정
  api_server/src/model/Likes.deprecated.ts
  api_server/src/model/Provider.ts
  api_server/src/repository/HistoryRepository.ts
  api_server/src/repository/LikesRepository.deprecated.ts
  api_server/src/repository/providerRepository.deprecated.ts
  api_server/src/repository/providerRepository.ts
  api_server/src/router/articleRouter.ts
  api_server/src/router/bookmarkRouter.ts
  api_server/src/router/likesRouter.deprecated.ts
  api_server/src/router/likesRouter.ts
  api_server/src/router/providerRouter.ts
  api_server/src/service/articleService.deprecated.ts
  api_server/src/service/providerService.ts
  api_server/src/type/ProviderType.ts
  front/src/components/BlogCardLayout/BlogCard/BlogCard.tsx
  front/src/pages/api/auth/[...nextauth].ts
  front/src/pages/api/provider/me.ts
  front/src/pages/api/provider/rss.ts
  front/src/types/blog.d.ts
  front/src/types/response.d.ts
  front/src/wrapper/withCheckJwt.ts
Labels: 👀 리뷰 필요

#69 탑 버튼 추가
  front/src/components/Common/Icon/svg/index.ts
  front/src/components/Common/Icon/svg/top.svg
  front/src/components/Modal/Modal.tsx
  front/src/components/TopButton/TopButton.tsx
  front/src/components/TopButton/index.tsx
  front/src/components/TopButton/styles.ts
  front/src/lib/styles/theme.ts
  front/src/pages/bookmark.tsx
  front/src/pages/index.tsx
  front/src/pages/privacy.tsx
  front/src/pages/profile.tsx
  front/src/pages/term.tsx
  front/src/types/styled.d.ts
Labels: 🔧 기능
