Repository LM-channel-team-project/kiwee.dev, pull requests merged in 2021-05, with the labels that each got.

#5 레이아웃, 글로벌 스타일, 라이트, 다크 테마 추가
  front/src/components/AppLayout/AppLayout.tsx
  front/src/components/AppLayout/index.ts
  front/src/components/Footer/Footer.tsx
  front/src/components/Footer/index.ts
  front/src/components/header/Header.tsx
  front/src/components/header/HeaderAuth.tsx
  front/src/components/header/HeaderPreference.tsx
  front/src/components/header/HeaderUserProfile.tsx
  front/src/components/header/index.ts
  front/src/lib/styles/GlobalStyle.ts
  front/src/lib/styles/index.ts
  front/src/lib/styles/theme.ts
  front/src/pages/_app.tsx
  front/src/types/styled.d.ts
  front/yarn.lock
Labels: 👀 리뷰 필요

#7 svg 아이콘 컴포넌트 추가
  .gitignore
  front/src/components/Common/Icon/Icon.tsx
  front/src/components/Common/Icon/index.ts
  front/src/components/Common/Icon/svg/bookmark.svg
  front/src/components/Common/Icon/svg/index.ts
  front/src/components/Common/Icon/svg/like.svg
  front/src/components/Common/Icon/svg/setting.svg
  front/src/types/image.d.ts
Labels: 👀 리뷰 필요

#6 OAuth2.0 로그인 API 엔드포인트 추가
  api_server/package.json
  api_server/src/model/RssProvider.ts
  api_server/src/repository/RssProviderRepository.ts
  api_server/src/router/providerRouter.ts
  api_server/src/rssParser.ts
  api_server/src/secure/jwt.ts
  api_server/src/server.ts
  api_server/src/type/RssProviderType.ts
  api_server/tsconfig.json
  api_server/yarn.lock
  rss_batch_crawler/src/model/RssProvider.ts
  rss_batch_crawler/src/repository/RssProviderRepository.ts
  rss_batch_crawler/src/type/RssProviderType.ts
Labels: 👀 리뷰 필요, 🔧 기능

#8 다크모드 구현
  front/src/components/Settings/Settings.tsx
  front/src/components/Settings/ToggleDarkmode/ToggleDarkmode.tsx
  front/src/components/Settings/ToggleDarkmode/index.tsx
  front/src/components/Settings/ToggleDarkmode/styles.ts
  front/src/components/Settings/common/styles.ts
  front/src/components/Settings/index.tsx
  front/src/components/Settings/styles.ts
  front/src/components/header/Header.tsx
  front/src/components/header/HeaderPreference.tsx
  front/src/context/ThemeContext.tsx
  front/src/hooks/useThemeContext.ts
  front/src/lib/styles/theme.ts
  front/src/pages/_app.tsx
  front/src/types/styled.d.ts
Labels: 👀 리뷰 필요, 🔧 기능

#10 텍스트 버튼, 아이콘 버튼 추가
  front/src/components/Common/Button/Button.tsx
  front/src/components/Common/Button/Icon/IconButton.tsx
  front/src/components/Common/Button/Icon/index.ts
  front/src/components/Common/Button/Text/TextButton.tsx
  front/src/components/Common/Button/Text/index.ts
  front/src/components/Common/Button/button.d.ts
  front/src/components/Common/Button/index.ts
  front/src/components/Common/Button/index.tsx
  front/src/components/Common/Button/style.ts
  front/src/components/Common/Icon/svg/bookmark.svg
  front/src/components/Common/Icon/svg/like.svg
  front/src/components/Common/Icon/svg/setting.svg
Labels: 👀 리뷰 필요, 🔧 기능

#18 새로운 탭에서 열기 기능 구현
  front/src/components/PostCardLayout/PostCard/PostCard.tsx
  front/src/components/PostCardLayout/PostCard/styles.ts
  front/src/components/Settings/Settings.tsx
  front/src/components/Settings/ToggleNewTab/ToggleNewTab.tsx
  front/src/components/Settings/ToggleNewTab/index.tsx
  front/src/components/Settings/styles.ts
  front/src/context/NewTabContext.tsx
  front/src/context/ThemeContext.tsx
  front/src/hooks/useNewTabContext.ts
  front/src/pages/_app.tsx
Labels: 👀 리뷰 필요, 🔧 기능

#19 Next-Auth 모듈 추가
  front/.gitignore
  front/package.json
  front/src/components/header/HeaderAuth.tsx
  front/src/pages/_app.tsx
  front/src/pages/api/auth/[...nextauth].ts
  front/src/pages/api/me.ts
  front/src/pages/index.tsx
  front/src/types/env.d.ts
  front/src/wrapper/withCheckJwt.ts
  front/yarn.lock
Labels: 👀 리뷰 필요

#20 프로필 페이지 작업
  front/src/.env.example
  front/src/components/AppLayout/AppLayout.tsx
  front/src/components/Profile/ProfileStats.tsx
  front/src/components/Profile/ProfileStatsItem.tsx
  front/src/components/Profile/ProfileStatsPostCardList.tsx
  front/src/components/Profile/ProfileUser.tsx
  front/src/lib/api/client.ts
  front/src/lib/styles/theme.ts
  front/src/pages/api/test/auth/me.ts
  front/src/pages/profile.tsx
  front/src/types/env.d.ts
  front/src/types/styled.d.ts
Labels: 👀 리뷰 필요, 🔧 기능

#22 Modal과 Login 스타일링 및 Header에 프로필 생성
  front/src/components/Common/Icon/svg/close.svg
  front/src/components/Common/Icon/svg/github.svg
  front/src/components/Common/Icon/svg/google.svg
  front/src/components/Common/Icon/svg/index.ts
  front/src/components/Common/Modal/Modal.tsx
  front/src/components/Login/Login.tsx
  front/src/components/Login/index.ts
  front/src/components/Login/styles.ts
  front/src/components/Modal/Modal.tsx
  front/src/components/Modal/index.ts
  front/src/components/PostCardLayout/PostCard/PostCard.tsx
  front/src/components/Profile/ProfileDetails.tsx
  front/src/components/Profile/ProfileUser.tsx
  front/src/components/header/Header.tsx
  front/src/components/header/HeaderAuth.tsx
  front/src/lib/styles/theme.ts
  front/src/pages/_app.tsx
  front/src/pages/index.tsx
  front/src/types/styled.d.ts
Labels: 👀 리뷰 필요, 🔧 기능

#27 article paging response의 likes 속성 추가
  api_server/src/router/articleRouter.ts
  api_server/src/router/providerRouter.ts
  api_server/src/service/articleService.ts
  api_server/src/type/ArticleType.ts
  front/src/types/response.ts
Labels: 👀 리뷰 필요, 🔧 기능

#28 환경변수 설정
  front/.env.example
  front/src/.env.example
  front/src/config/constants.ts
  front/src/config/constants/api.ts
  front/src/config/constants/database.ts
  front/src/config/constants/env.ts
  front/src/config/constants/index.ts
  front/src/config/constants/nextAuth.ts
  front/src/lib/api/client.ts
  front/src/pages/api/auth/[...nextauth].ts
  front/src/types/env.d.ts
Labels: ⚡️ 심플

#29 좋아요 기능 추가
  front/src/components/PostCardLayout/PostCard/PostCard.tsx
  front/src/components/PostCardLayout/PostCardLayout.tsx
  front/src/hooks/useGetData.ts
  front/src/pages/index.tsx
  front/src/types/article.d.ts
Labels: 👀 리뷰 필요, 🔧 기능

#30 useRequest, useGetMe 추가, 프로필 페이지 수정
  front/src/components/Profile/ProfileUser.tsx
  front/src/hooks/swr/useGetMe.ts
  front/src/hooks/swr/useRequest.ts
  front/src/lib/api/index.ts
  front/src/pages/profile.tsx
  front/src/types/apiType.d.ts
  front/src/types/response.d.ts
Labels: 👀 리뷰 필요

#31 환경변수 변경에 따른 api url 변경
  front/src/pages/index.tsx
Labels: ⚡️ 심플

#32 [FIX] m1 macOS 치명적 에러 해결
  front/package.json
  front/yarn.lock
Labels: ⚡️ 심플

#33 좋아요 버튼 클릭 시 색상 변경
  front/src/components/PostCardLayout/PostCard/PostCard.tsx
  front/src/lib/styles/theme.ts
  front/src/types/styled.d.ts
Labels: ⚡️ 심플

#34 무한스크롤 오류 해결
  front/src/hooks/useInfiniteScroll.ts
  front/src/pages/index.tsx
Labels: 🔧 기능

#35 이슈 #25 API 추가
  api_server/src/model/History.ts
  api_server/src/model/Provider.ts
  api_server/src/repository/ArticleRepository.ts
  api_server/src/repository/HistoryRepository.ts
  api_server/src/repository/providerRepository.ts
  api_server/src/router/articleRouter.ts
  api_server/src/router/bookmarkRouter.ts
  api_server/src/router/historyRouter.ts
  api_server/src/router/likesRouter.ts
  api_server/src/router/providerRouter.ts
  api_server/src/server.ts
  api_server/src/service/articleService.ts
  api_server/src/service/bookmarkService.ts
  api_server/src/service/historyService.ts
  api_server/src/service/providerService.ts
  api_server/src/type/HistoryType.ts
  api_server/src/type/ProviderType.ts
  front/src/pages/api/article/index.ts
  front/src/pages/api/bookmarks/index.ts
  front/src/pages/api/history/index.ts
  front/src/pages/api/provider/bookmark.ts
Labels: 👀 리뷰 필요, 🔧 기능

#36 Suspense와 ErrorBoundary를 사용하여 비동기 처리하기
  front/package.json
  front/src/components/AsyncBoundary/AsyncBoundary.tsx
  front/src/components/AsyncBoundary/ErrorBoundary/ErrorBoundary.tsx
  front/src/components/AsyncBoundary/ErrorBoundary/index.ts
  front/src/components/AsyncBoundary/SSRSafeSuspense/SSRSafeSuspense.tsx
  front/src/components/AsyncBoundary/SSRSafeSuspense/index.ts
  front/src/components/AsyncBoundary/index.ts
  front/src/components/ErrorFallback/Profile/ProfileUserFallback.tsx
  front/src/components/ErrorFallback/SkeletonBlock.tsx
  front/src/components/Profile/ProfileUser.tsx
  front/src/components/Skeleton/Profile/SkeletonProfileUser.tsx
  front/src/hooks/swr/useDeleteErrorCache.ts
  front/src/hooks/swr/useGetMe.ts
  front/src/hooks/useMounted.ts
  front/src/pages/profile.tsx
  front/yarn.lock
Labels: 👀 리뷰 필요
